sonar.projectKey=mern-stack
sonar.projectName=MERN Stack DevSecOps
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/*.test.js
sonar.sourceEncoding=UTF-8
