apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: 371397508701.dkr.ecr.ap-south-1.amazonaws.com/mern-backend:v64

          ports:
            - containerPort: 3500
          env:
            - name: MONGO_CONN_STR
              value: "mongodb://mongodb:27017/todos"
